export const CHANGE_LOCK_STATUS = "CHANGE_LOCK_STATUS";

export const READY = "READY";

export const SET_LOCKING = "SET_LOCKING";
export const SET_UNLOCKING = "SET_UNLOCKING";

export const ERROR = "ERROR";

export const SET_BOX_PASSCODE = "SET_BOX_PASSCODE";

export const UPDATE_PASSCODE = "UPDATE_PASSCODE";

export const UPDATE_SCREEN = "UPDATE_SCREEN";

export const SET_SCREEN_OFF_TIMER = "SET_SCREEN_OFF_TIMER";
export const SET_CHECK_PASSCODE_TIMER = "SET_CHECK_PASSCODE_TIMER";

export const CLEAR_SCREEN_OFF_TIMER = "CLEAR_SCREEN_OFF_TIMER";
export const CLEAR_CHECK_PASSCODE_TIMER = "CLEAR_CHECK_PASSCODE_TIMER";

export const ENTERING_PASSCODE = "ENTERING_PASSCODE";

export const SERVICE = "SERVICE";

export const VALIDATING = "VALIDATING";

export const RESET = "RESET";

export const DISABLE_BUTTONS = "DISABLE_BUTTONS";
export const ENABLE_BUTTONS = "ENABLE_BUTTONS";
